# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03fd7c74ca1b73bf78102631ac2978330268f2a3696364674317a79fcc35c279f521c5a9ffbcd45b3b19244604852eacdc1eae0931109a819de618b0f96a8f1e

test:
  secret_key_base: 355cdca7118810aacdc75c047d34164869ce4fcac68e6c088c4cbbd0c72554019d0a43869e1969fb183f9eea776e08eda7a81f65be569095e9f4c8ef88af2d4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
